### ISSUE TITLE
Submitted job is missing a username

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#866] opened 2023-11-15 22:05 UTC
But @bsatoriu says it is showing up in figaro  
And once it fails it shows up

Maybe this is related to this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c7ec347a07a59d987cf5b528026b1fc89c9e4ad/Screenshot%202023-11-15%20at%202.06.40%20PM.png)
? but queued isn't an option for me and the queued job doesn't show up even when I unselect this

**Comment by bsatoriu** [comment] 2023-11-15 22:42
@grallewellyn I'm seeing queued jobs in OPS after subsequent testing. The initial problem of the missing queued job appears to have been caused by a missing username associated to my original job. Somehow, after submitting my initial job, no username was assigned to the job metadata and, therefore, went missing in HySDS as a user-less job. It appears the username was [not included in the payload](https://github.com/MAAP-Project/maap-api-nasa/blob/master/api/utils/hysds_util.py#L389-L393) from ADE to the MAAP API.

<img width="1127" alt="Screenshot 2023-11-15 at 2 33 50 PM" src="https://github.com/MAAP-Project/Community/assets/27687558/219f976d-ab5a-4ec0-95f6-07d1ba29e391">

**Comment by bsatoriu** [comment] 2023-11-15 23:01
The username property that the Jupyter DPS extension is sending originates from this function: https://github.com/MAAP-Project/dps-jupyter-extension/blob/861ff55c8842c8b5334f5db0fdc6b7cf5109c543/src/utils/utils.ts#L50

In my case, it may be that my username was missing briefly while being reset from Keycloak? It seems like an edge case that we can just monitor and investigate later if it recurs.

**Comment by grallewellyn** [comment] 2023-11-15 23:46
Figaro looks like this:
<img width="705" alt="Screenshot 2023-11-15 at 3 43 32 PM" src="https://github.com/MAAP-Project/Community/assets/114033465/6e9b0286-be53-46a4-ad70-fa94f203d253">
and test33 isn't showing up on my jobs list
Although the console has 
<img width="387" alt="Screenshot 2023-11-15 at 3 44 17 PM" src="https://github.com/MAAP-Project/Community/assets/114033465/8d1d13bc-4f6f-4817-9433-7a5efb17ffa5">
and never indicates there was a problem getting the username

Next steps are I am going to add some print statements in dps to see if the frontend is submitting the username with the request

We believe this issue is different than the issue where a job might not show up when it is in the queued state, but then shows up when it is in the failed state

**Comment by grallewellyn** [comment] 2023-11-29 22:01
This is happening fairly consistently for me. Here are some console logs
<img width="1176" alt="Screenshot 2023-11-29 at 9 12 06 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/cea3ffc8-c7d8-4e4d-b9d7-d51e807d5042">
You can see in the highlighted line that dps-jupyter-extension successfully got my username when we launched the submit jobs window, however the job was still submitted with the username being `null`
Expanded version of same console logs, just showing what happens when submitJob 

<img width="1164" alt="Screenshot 2023-11-29 at 9 14 00 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/c5c6986a-ef88-45e5-9fae-dbcf73daf595">

It seems pretty consistent that the username is being sent as `null` when you stop and restart a workspace, then open the submit jobs tab and submit a job. If you stop and restart a workspace then open the view jobs tab first or ay any point, then the username is correctly set and sent when you submit a job. I believe this is because this function
```
export const userInfoSlice = createSlice({
  name: 'UserInfo',
  initialState,
  reducers: {
    resetUsername: () => initialState,
    setUsername: (state, action) => {
      state.username = action.payload
    },
  },
})
```
Is not being called when you just open the submit jobs tab. This function is only called when you open the view jobs tab 

So I think this shouldn't be too difficult of a fix @marjo-luc @bsatoriu

**Closed as completed** 2024-01-22 22:23 UTC
