### ISSUE TITLE
MAAP Admin interface doesn't pad dates, makes sorting confusing

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#606] opened 2022-10-14 18:25 UTC
When I tried to sort to find out the latest users who have requested access by date, it doesn't display it in chronological order.

![Screen Shot 2022-10-14 at 11.24.13 AM.png](https://images.zenhubusercontent.com/5ee7da582a6c07a5f569db2e/60c78036-ad6f-4804-b49d-b41adbaa22e6)

**Comment by anilnatha** [comment] 2022-10-17 20:40
@gchang Can you test this again on your machine and let me know if the issue is still present? I tried to replicate the issue using Chrome and Firefox on my machine and am unable to replicate it.

|DIT|UAT|OPS|
|---|---|---|
|<img width="233" alt="image" src="https://user-images.githubusercontent.com/931107/196277706-6f099310-cbc2-4b86-8c96-24aad7b034aa.png">|<img width="225" alt="image" src="https://user-images.githubusercontent.com/931107/196278719-0655afa6-cfd5-40d1-ad81-65b6c394b549.png">|<img width="186" alt="image" src="https://user-images.githubusercontent.com/931107/196278816-92cd3bbd-c134-429d-9738-0df5171f3428.png">

**Comment by anilnatha** [comment] 2022-10-17 20:44
@gchang Disregard my last post, was able to replicate the issue in Safari (Version 16.0 (17614.1.25.9.10, 17614))

**Comment by anilnatha** [comment] 2022-10-17 21:33
Issue is resolved, simply needed to prepend the day value with `0` to fix sorting.   The fix has been rolled out to DIT, UAT, and OPS.

@oddes ready to test the WordPress MAAP Admin Plugin user's list view.  Since this is already deployed to OPS, feel free to close if your testing passes.  Thank you!

**Comment by oddes** [comment] 2022-10-20 04:53
![Screen Shot 2022-10-19 at 9.52.43 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/a45f23ff-3061-4157-96fd-77c30ab924f7)

**Closed by oddes** 2022-10-20 04:53 UTC
Labels: UI
