### ISSUE TITLE
UWG reports workspace bugginess

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#875] opened 2023-11-29 23:37 UTC
Workspaces having some bugginess, new features periodically disappearing, lots of restarts forcing new downloads / installs of packages slowing things down.

**Comment by bsatoriu** [comment] 2024-01-10 01:43
Possible duplicate of https://github.com/MAAP-Project/Community/issues/807

**Closed as completed** 2024-02-01 21:40 UTC
Labels: ADE
