### ISSUE TITLE
Downloading files to workspace, occasionally strange error

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#210] opened 2020-11-01 17:50 UTC
**Describe the bug**
Downloading files to workspace (r2d2) in large volumes (GEDI and ICESat-2). For ICESat-2 this works well most of the time, but occasionally fails showing the following error. If I skip that file, the rest seem OK but this happens fairly frequently. This error was for ICESat-2 v 3 granules.
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-17-bbe9e70eb794> in <module>
     20     else:
     21         print(f)
---> 22         gedi_granules[f].getLocalPath(download_dir)
     23 print(count)

/opt/conda/lib/python3.7/site-packages/maapPy-0.3.0-py3.7.egg/maap/Result.py in getLocalPath(self, destpath, overwrite)
     37             if not overwrite and not os.path.isfile(destpath + "/" + filename):
     38                 s3 = boto3.client('s3', aws_access_key_id=self._awsKey, aws_secret_access_key=self._awsSecret)
---> 39                 s3.download_file(o.netloc, o.path.lstrip('/'), destpath + "/" + filename)
     40 
     41             return destpath + '/' + filename

/opt/conda/lib/python3.7/site-packages/boto3-1.16.8-py3.7.egg/boto3/s3/inject.py in download_file(self, Bucket, Key, Filename, ExtraArgs, Callback, Config)
    170         return transfer.download_file(
    171             bucket=Bucket, key=Key, filename=Filename,
--> 172             extra_args=ExtraArgs, callback=Callback)
    173 
    174 

/opt/conda/lib/python3.7/site-packages/boto3-1.16.8-py3.7.egg/boto3/s3/transfer.py in download_file(self, bucket, key, filename, extra_args, callback)
    305             bucket, key, filename, extra_args, subscribers)
    306         try:
--> 307             future.result()
    308         # This is for backwards compatibility where when retries are
    309         # exceeded we need to throw the same error from boto3 instead of

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267 

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/tasks.py in _main(self, transfer_future, **kwargs)
    253             # Call the submit method to start submitting tasks to execute the
    254             # transfer.
--> 255             self._submit(transfer_future=transfer_future, **kwargs)
    256         except BaseException as e:
    257             # If there was an exception raised during the submission of task

/opt/conda/lib/python3.7/site-packages/s3transfer-0.3.3-py3.7.egg/s3transfer/download.py in _submit(self, client, config, osutil, request_executor, io_executor, transfer_future, bandwidth_limiter)
    341                 Bucket=transfer_future.meta.call_args.bucket,
    342                 Key=transfer_future.meta.call_args.key,
--> 343                 **transfer_future.meta.call_args.extra_args
    344             )
    345             transfer_future.meta.provide_transfer_size(

/opt/conda/lib/python3.7/site-packages/botocore-1.19.8-py3.7.egg/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

/opt/conda/lib/python3.7/site-packages/botocore-1.19.8-py3.7.egg/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**To Reproduce**
Ran this (note, these are called gedi but are actually ICESat-2 granules, as I couldn't get more than a single GEDI granule at a time with similar script).

gedi_granules=maap.searchGranule(concept_id="C1200235747-NASA_MAAP", limit=10000, bounding_box="7.0,-7.0,34.0,8.0")

count=0
for f in range(764, len(gedi_granules)):
    #ID = s[f]['Granule']['DataGranule']['ProducerGranuleId']
    ID = gedi_granules[f]['Granule']['OnlineAccessURLs']['OnlineAccessURL']['URL']                    
    #print(ID)
    count=count+1
    download_dir = '/projects/r2d2/gedi_test_granules'
    existingfiles = [file for file in os.listdir(download_dir)]
    if ID in existingfiles:
        print('file exists...')
    else:
        print(f)
        gedi_granules[f].getLocalPath(download_dir)    
print(count) 

**Expected behavior**
Expected granules to dowload to the workspace.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gchang** [comment] 2020-11-03 21:50
Looks like a duplicate of #211

**Closed** 2020-11-03 21:50 UTC
