### ISSUE TITLE
Setup DPS on GCC and update references in ADE 

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#162] opened 2020-08-27 23:57 UTC
Deploy DPS to the GCC environment, and update any references in ADE to the GCC DPS: principally, MAAP API settings.

**Comment by gchang** [comment] 2021-01-27 23:36
This is still valid and open.

**Comment by gchang** [comment] 2021-03-18 20:24
Dupe of #257 and #282

**Closed by gchang** 2021-03-18 20:24 UTC
Labels: ADE, API, DPS, Duplicate, JPL
