### ISSUE TITLE
Cut new stable release once everything is stable and ready on ops!

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#330] opened 2021-05-12 22:37 UTC
- [x] Cut new version v3.0 release
- [x] Update stable tag
- [x] Update ops devfiles to use stable tag (keep uat pointing at develop tag)

**Comment by marjo-luc** [comment] 2021-06-28 22:31
These updates have been made. Closure pending pull request approval and final testing.

Pull request: https://github.com/MAAP-Project/eclipse-che-devfile-registry/pull/2

**Comment by marjo-luc** [comment] 2021-06-29 02:44
Everything looks good except the EarthData Search proxy. The main widget opens with a 404 and the request url looks suspicious:
`https://ade.maap-project.org/serverxdstooou-ws-jupyter/server-3100/edsc/proxy/https://ade.maap-project.org:30052`

This will require some additional investigation.

**Comment by marjo-luc** [comment] 2021-06-29 18:46
I was unable to reproduce the issues I saw yesterday. All images loaded as expected and access to EarthData Search was successful. There were a couple times where images timed out on workspace spin-up, but retrying a second time worked. Closing this ticket for now and will open another ticket if the issue persists.

**Closed by marjo-luc** 2021-06-29 18:46 UTC
Labels: ADE, JPL
