### ISSUE TITLE
The MAAP button in Jupyter notebooks still has api.maap-project.org in the constructor

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#1042] opened 2024-08-07 15:26 UTC
**Describe the bug**
Recently we started to suggest instantiating maap with MAAP() rather than MAAP(‘api.maap-project.org’)
In a Jupyter notebook there’s a little “MAAP” button that pastes in the maap.py instantiation… it still has the old syntax

**Expected behavior**
Update to new recommendation on constructor

**Comment by grallewellyn** [comment] 2024-08-07 16:51
Duplicate of already completed issue: https://github.com/MAAP-Project/Community/issues/1029

**Closed as completed by grallewellyn** 2024-08-07 16:51 UTC
