### ISSUE TITLE
EDSC search filter is NOT copying correctly 

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#335] opened 2021-05-18 21:40 UTC
1. Login to Che in OPS workspace
2. Open EDSC and search for any dataset
3. Now, keep any filters [project, date] as shown below example
"generated from this EDSC search: https://ade.ops.maap-project.org:30052/search/granules?p=C1200110728-NASA_MAAP&pg[0][qt]=2016-01-15T00%3A00%3A00.000Z%2C2021-05-17T23%3A59%3A59.999Z&tl=1605461426!4!!
4. Now, paste the generated query to Che, you will notice it is only copying the concept if and limit, rest of the filters are not copied to Che.
maap.searchGranule(concept_id=“C1200110728-NASA_MAAP”, limit=1000)

**Comment by bsatoriu** [comment] 2022-08-16 19:41
This is a duplicate of #523

**Closed** 2022-08-16 19:45 UTC
Labels: Bug, JPL
